### PR TITLE
Fix global access

### PR DESCRIPTION
**Pull request by Python1320**

### CODE REVIEW

**Review by Techbot121 — CHANGES_REQUESTED** [review]
as per discord, it makes more sense to replace the one `ply:Nick()` to `arg:Nick()` instead.

**Comment by Python1320** [comment]
It does not because you can reasonably make the same mistake again within the same function. We refer to players as `ply` not as arg.

**Comment by Python1320** [comment]
If `local ply = arg` smells it is because the function is "fat" itself and that `if`-branch should be moved to its own function altogether.

**Comment by Earu** [comment]
Agree to disagree

**Pull request closed without merging**
